byte GenTree::bit_count[256];
int *GenTree::roots;
int *GenTree::left;
int *GenTree::ryte;
int *GenTree::parent;
int GenTree::ixRoots;
int GenTree::ixLeft;
int GenTree::ixRyte;
int GenTree::ixPrnt;
